version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.dockerfile
    ports:
      - "8098:80"
    volumes:
      - ./:/var/www/QuintusTask2
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.dockerfile
    volumes:
      - ./:/var/www/QuintusTask2
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quintus
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
